language: go

os:
  - linux
  - windows

go:
  - 1.13.x
env:
  - GO111MODULE=on
install:
  - go get -u honnef.co/go/tools/cmd/staticcheck
  - go get -u github.com/client9/misspell/cmd/misspell

before_script:
  - cd nats;go build  ;cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then
      GO_LIST=$(go list ./...) &&
      $(exit $(go fmt $GO_LIST | wc -l)) &&
      go vet $GO_LIST &&
      find . -type f -name "*.go" | xargs misspell -error -locale US &&
      staticcheck -f stylish $GO_LIST ;
    fi

script:
  - set -e
  - go test -v --failfast -p=1 ./...
  - set +e
